### ISSUE TITLE
Sell not working?

### ISSUE THREAD

**Issue by ssithuxz** [gobeli/pump-and-dump#1]
everytime i buy, it does not sell immediate after.

always say "insufficient funds" even though i did buy the token

maybe put a small delay before making bot sell??

**Comment by jurandfantom** [comment]
propably because of that small 0.25 %Bittrex tax

**Comment by ssithuxz** [comment]
that doesnt make sense...

if you buy and get say 100 omg

it should sell 100 omg

why does fee matter?

**Comment by jurandfantom** [comment]
hmm you right, probably that because of to small wait time before sell... lucky for us, even if sell dosn't work correctly, we still have time to setup sell order, best price stay quite long :) I can't wait to use that bot.  Wonder how many people use it or other similar.

**Comment by gobeli** [comment]
The sell order only gets dispatched if the buy order was successful. (https://github.com/gobeli/pump-and-dump/blob/master/src/renderer/components/ExecuteModal.vue#L86)

Feel free to open the issue up again if you have any further questions.
