### ISSUE TITLE
Unable to accèss cryptopia getting failed error

### ISSUE THREAD

**Issue by sudhir7890** [gobeli/pump-and-dump#13]

**Comment by gobeli** [comment]
Have you checked your API key, internet connection and selected a market?
Furthermore could you provide the error message?

**Comment by sudhir7890** [comment]
what are the strategies and do you have a some methods to keep before
pumps.

**Comment by sudhir7890** [comment]
The screenshot in GitHub looks different than this, could once explain how
this works or at least a small video. to add strategies.


<img width="1680" alt="screen shot 2018-01-22 at 8 10 12 am" src="https://user-images.githubusercontent.com/22940553/35225036-cee3883a-ff4c-11e7-9551-c35dc4afc149.png">

**Comment by sudhir7890** [comment]
Do you have a setup file for Mac ?

**Comment by gobeli** [comment]
OSX is on the way, will be here as soon as the travis-ci job goes through: https://travis-ci.org/gobeli/pump-and-dump/jobs/331820341

**Comment by gobeli** [comment]
there you go https://github.com/gobeli/pump-and-dump/releases/tag/0.3.0-alpha2

**Comment by sudhir7890** [comment]
Unable to copy and paste the api key in OSX .dmg

**Comment by gobeli** [comment]
closing this one since you opened another one
