### ISSUE TITLE
Doesn't work on Windows 32 Bit

### ISSUE THREAD

**Issue by agusridwan** [gobeli/pump-and-dump#14]
Can you make it compatible with with Windows 32 bit?
Thank you

**Comment by gobeli** [comment]
I can't quit figure out how to deploy multiple platforms to GitHub, but you can get it [here](https://ci.appveyor.com/project/gobeli/pump-and-dump/build/job/myynnl4dlfeu40qf/artifacts)

**Comment by sudhir7890** [comment]
I have a macbook. Doesn't have windows, Can I install in Mac ?

**Comment by gobeli** [comment]
On the way, OSX stuff is a bit slow on travis

**Comment by sudhir7890** [comment]
any video or tutorial for latest version which you had for the windows. how
to setup multiple strategies and multiple sells. as we had a pump in 7
hours.

**Comment by gobeli** [comment]
Unfortenatly you currently can only have one sell, you just fill out the form with volume, buy at % and sell at % and then click use. As soon as you click Ok on the modal, one buy and one sell order will be dispatched to your exchange

**Comment by sudhir7890** [comment]
with volume :  is how much btc I want to spend ??

by % :  10 %

sell:  30%

**Comment by gobeli** [comment]
exactly

**Comment by sudhir7890** [comment]
does it works the same ? if I clone  from GitHub and run through the
terminal ? as we don't have on OSX.

**Comment by gobeli** [comment]
sure, you can just clone the project and run npm run dev, works exactly the same

**Comment by sudhir7890** [comment]
yeah done it. But unable to give less than 1 btc . its redirecting  to 1btc
if am trying to 0.01 btc

**Comment by sudhir7890** [comment]
Got this error, when I click on use.

**Comment by gobeli** [comment]
volume input will be fixed with the next release, please open a separate issue with your error, furthermore I can't see your images if you attach them to an email....
