### ISSUE TITLE
HitBTC - Trade with ETH

### ISSUE THREAD

**Issue by CarlightExpress** [gobeli/pump-and-dump#16]
Hi There

I noticed int he UI that there is only an option for "Volume BTC" but it allows you to select coins with an /ETH for example DCN/ETH

Does the "Volume BTC" trade Etherium for the above example coin?

**Comment by gobeli** [comment]
This is resolved with the latest [release](https://github.com/gobeli/pump-and-dump/releases/tag/0.3.0-alpha2)
