### ISSUE TITLE
Remove the Confirmation box please

### ISSUE THREAD

**Issue by CarlightExpress** [gobeli/pump-and-dump#17]
As we all know, P&D is all about speed, having the confirmation box to confirm the buy and sell just adds more time to get the best price, can we remove that, or have an option to "Not show this again", I know there's a risk involved, but timing is the essence :-)

**Comment by iagreewiththeguyabove** [comment]
Just made an account just to agree with the guy above. ^ 
I was gonna post this as an issue myself. The confirmation box makes you lose quite a lot of value in pump. Please make it so that theres a setting you can choose for it to show or to not show that.

**Comment by txxxc** [comment]
For speed reasons, it's also a good idea to change market selector. Instead of a drop-down, make it two fields: Quote and Base. So we can set the Base currency (e.g. BTC) beforehand, and then at the time of the pump just type in the Quote currency.

**Comment by gobeli** [comment]
Added in alpha3
