### ISSUE TITLE
Fetch Orders is not supportet by bitcoincoid

### ISSUE THREAD

**Issue by ViperSoul** [gobeli/pump-and-dump#19]
can you make this software to fetch order in bitcoincoid...?

I am from Indonesia and I appreciate your work..
thank you very much...

![fetch](https://user-images.githubusercontent.com/35815048/35406946-dd0b9bbc-023c-11e8-8d4c-1566058c9283.png)

**Comment by gobeli** [comment]
Unfortunately I am bound to ccxt, which means as long as its not supported there it's not supported in this tool... https://github.com/ccxt/ccxt/blob/master/js/bitcoincoid.js#L22

**Comment by gobeli** [comment]
This could be possible since it just doesn't support fetchorders, but it does fetchopenorders and fetchclosedorders: https://github.com/ccxt/ccxt/blob/master/js/bitcoincoid.js#L22

**Comment by ViperSoul** [comment]
what must i do? i dont understand program.. -_-
only your bot works for bitcoincoid., i can not find any other bot out there..

**Comment by gobeli** [comment]
Im pretty swamped right now but I'll get to it as soon as possible, the only thing which needs changing is the way the orders get fetched

**Comment by ViperSoul** [comment]
okayy thankyou very much... ^^

**Comment by gobeli** [comment]
Should work with alpha3
