### ISSUE TITLE
Rearange buttons position

### ISSUE THREAD

**Issue by jurandfantom** [gobeli/pump-and-dump#2]
Better setup would be adding buy button right next to coin name + additional option to setup before with buy option we would like to use. Example 
##MEME### ##BUY## ##1##

No.   Volume       Buy at      Sell at
1        0.1 BCT      3%           10%
2        2.0 BCT      5%           20%

**Comment by gobeli** [comment]
So would you like to start without the modal window?

Your second request is currently on my todo list for future releases
