### ISSUE TITLE
Sell All Coins - Option? (for bad pumps?

### ISSUE THREAD

**Issue by cinemano** [gobeli/pump-and-dump#23]
Hi .. could you share a "Add Strategy" suggestion to act as a "sell at any cost" sale option for when a coin suddenly drops in value before reaching sales target? or a cancel all option button would be amazing

**Comment by gobeli** [comment]
There actually is a sell all option implemented.... https://github.com/gobeli/pump-and-dump/blob/102e117884c94d6aa77f9dedb75d20fa2e30b343/src/renderer/components/Main.vue#L45
