### ISSUE TITLE
 invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting

### ISSUE THREAD

**Issue by vrey89** [gobeli/pump-and-dump#26]
binance POST https://api.binance.com/api/v3/order 400 {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)

**Comment by jaNGOB** [comment]
This mostly happens on the users end. Have you synched you clocks and do you keep them synched?
Use google to search for 3rd  party programs to regularly synch your clock.

**Comment by vrey89** [comment]
ah yep it is, I restarted the computer and worked, now works again. Thanks
