### ISSUE TITLE
keeps GIVING ME INVALID API !

### ISSUE THREAD

**Issue by dr3ad3d** [gobeli/pump-and-dump#3]

**Comment by gobeli** [comment]
I am going to need more information to help you... probably the API-Key and Secret that you entered are invalid

**Comment by afblaze94** [comment]
I am having the same problem too.
I use the same API and Secret in my mobile apps and it works.
Definitely not a problem from my side. May I know did you update the API url to version 1.1?

**Comment by ktemur** [comment]
Try to use a different new API Key which you dont use in any other application and then it is ok...

**Comment by gobeli** [comment]
@afblaze94 you could be right, i'll update the npm package
Could you try it out with the latest version?

**Comment by afblaze94** [comment]
It seems to be working fine now @gobeli 
Thanks... I'm still learning coding. Hope one day I will be able to contribute by writing my own bots!
