### ISSUE TITLE
bittrex ban ?

### ISSUE THREAD

**Issue by cristian7477** [gobeli/pump-and-dump#4]
[http://uk.businessinsider.com/bittrex-warning-cryptocurrency-pump-and-dump-scams-market-manipulation-2017-11](url)

**Comment by gobeli** [comment]
The goal of this project is to make an even ground for everyone participating, if pump-and-dumps are are banned, the ground is even as well ;) (https://bitcointalk.org/index.php?topic=2108541.0)
