### ISSUE TITLE
Add Strategy part is missing

### ISSUE THREAD

**Issue by ktemur** [gobeli/pump-and-dump#5]
I cannot see any place to add and save strategy as it is shown in screenshots, is it removed in last release? There is just use strategy button...
![capture](https://user-images.githubusercontent.com/4351824/34330522-db123f40-e92e-11e7-853f-fed4156fc67a.JPG)

**Comment by gobeli** [comment]
You can only use one strategy and that one will get applied right away (with the use button) similar to http://getcryptostorm.com/
