### ISSUE TITLE
Binance integration

### ISSUE THREAD

**Issue by ghost** [gobeli/pump-and-dump#8]
Binance is one of the biggest Crypto exchange, definitely worth some integration

**Comment by gobeli** [comment]
Dupe of #7 Since this would be resolved with integrating ccxt

**Comment by ghost** [comment]
Possible ETA?

**Comment by gobeli** [comment]
Hard to say I'm currently in the middle of uni exams, but if you have knowledge in JS I'd be more than happy to accept a PR :)

**Comment by ghost** [comment]
Nope, I am using ps/bash/ruby for scripting. JS is totally unknown area for me :(
